import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { twMerge } from 'tailwind-merge'

import { Sidebar } from '@/components'

import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={twMerge(
            'lg:grid-cols-app min-h-screen lg:grid',
            'dark:bg-zinc-900',
          )}
        >
          <Sidebar />

          <main className="min-w-0 px-4 pt-24 pb-12 lg:col-start-2 lg:px-8 lg:pt-8 lg:pb-12">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
