export const TIMEZONES = [
  {
    countryCode: 'BR',
    label: 'Brazil (São Paulo)',
    value: 'America/Sao_Paulo',
  },
  {
    countryCode: 'BR',
    label: 'Brazil (Fortaleza)',
    value: 'America/Fortaleza',
  },
  { countryCode: 'BR', label: 'Brazil (Manaus)', value: 'America/Manaus' },
  {
    countryCode: 'BR',
    label: 'Brazil (Rio Branco)',
    value: 'America/Rio_Branco',
  },
  { countryCode: 'US', label: 'USA (New York)', value: 'America/New_York' },
  { countryCode: 'US', label: 'USA (Chicago)', value: 'America/Chicago' },
  { countryCode: 'US', label: 'USA (Denver)', value: 'America/Denver' },
  {
    countryCode: 'US',
    label: 'USA (Los Angeles)',
    value: 'America/Los_Angeles',
  },
  {
    countryCode: 'MX',
    label: 'Mexico (Mexico City)',
    value: 'America/Mexico_City',
  },
  { countryCode: 'CA', label: 'Canada (Toronto)', value: 'America/Toronto' },
  {
    countryCode: 'GB',
    label: 'United Kingdom (London)',
    value: 'Europe/London',
  },
  { countryCode: 'FR', label: 'France (Paris)', value: 'Europe/Paris' },
  { countryCode: 'DE', label: 'Germany (Berlin)', value: 'Europe/Berlin' },
  { countryCode: 'ES', label: 'Spain (Madrid)', value: 'Europe/Madrid' },
  { countryCode: 'IT', label: 'Italy (Rome)', value: 'Europe/Rome' },
  { countryCode: 'RU', label: 'Russia (Moscow)', value: 'Europe/Moscow' },
  { countryCode: 'JP', label: 'Japan (Tokyo)', value: 'Asia/Tokyo' },
  { countryCode: 'CN', label: 'China (Shanghai)', value: 'Asia/Shanghai' },
  { countryCode: 'KR', label: 'South Korea (Seoul)', value: 'Asia/Seoul' },
  { countryCode: 'IN', label: 'India (Kolkata)', value: 'Asia/Kolkata' },
  { countryCode: 'AU', label: 'Australia (Sydney)', value: 'Australia/Sydney' },
  {
    countryCode: 'AR',
    label: 'Argentina (Buenos Aires)',
    value: 'America/Argentina/Buenos_Aires',
  },
  { countryCode: 'CL', label: 'Chile (Santiago)', value: 'America/Santiago' },
  {
    countryCode: 'ZA',
    label: 'South Africa (Johannesburg)',
    value: 'Africa/Johannesburg',
  },
  {
    countryCode: 'AE',
    label: 'United Arab Emirates (Dubai)',
    value: 'Asia/Dubai',
  },
  { countryCode: 'TR', label: 'Turkey (Istanbul)', value: 'Europe/Istanbul' },
  { countryCode: 'SG', label: 'Singapore', value: 'Asia/Singapore' },
  { countryCode: 'HK', label: 'Hong Kong', value: 'Asia/Hong_Kong' },
]
